// GENERATED by scripts/generate-base-parity-tests.mjs.
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.35;
import { BaseModuleTestDeploy } from "./BaseModuleTestDeploy.sol";
import { Vm } from "forge-std/Vm.sol";

import { ERC1967Proxy } from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
import { SplitRiskPoolFactory } from "../../contracts/SplitRiskPoolFactory.sol";
import { TestTimelockHelper } from "../helpers/TestTimelockHelper.sol";

abstract contract FactoryProxyTestBase is TestTimelockHelper {
    function _deployFactory(address initialOwner, address governanceTimelock, address poolImplementation)
        internal
        returns (SplitRiskPoolFactory deployedFactory)
    {
        SplitRiskPoolFactory implementation = SplitRiskPoolFactory(payable(BaseModuleTestDeploy.factory(Vm(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D))));
        bytes memory initData = abi.encodeWithSelector(
            SplitRiskPoolFactory.initialize.selector, initialOwner, governanceTimelock, poolImplementation
        );
        ERC1967Proxy proxy = new ERC1967Proxy(address(implementation), initData);
        deployedFactory = SplitRiskPoolFactory(payable(address(proxy)));
    }
}
