import {
    readdirSync,
    statSync,
    readFileSync,
    existsSync,
    mkdirSync,
    writeFileSync,
} from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";
import {
    CHAINLINK_CORE_INVENTORY,
    DEMO_EXTRA_INVENTORY,
    PYTH_CORE_INVENTORY,
    pythSequencerPolicyForChain,
    requiredReviewedCodehashPinNames,
    requireIndependentRpcOperators,
} from "./finalizeDeploymentManifest.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */`;

function getDirectories(path) {
    if (!existsSync(path)) {
        return [];
    }

    return readdirSync(path).filter(function (file) {
        return statSync(join(path, file)).isDirectory();
    });
}

function getFiles(path) {
    return readdirSync(path).filter(function (file) {
        return statSync(join(path, file)).isFile();
    });
}

function normalizeChainId(chainId) {
    if (chainId === undefined || chainId === null || chainId === "") {
        return null;
    }

    return String(chainId);
}

const LOCAL_CHAIN_IDS = new Set(["31337", "1337"]);
const ZERO_CODEHASH = `0x${"00".repeat(32)}`;
const TESTNET_SEQUENCER_EXCEPTION_SOURCES = new Set([
    "robinhood-testnet-explicit-exception",
    "robinhood-testnet-relaxed-guards",
]);

function validateSequencerUptimeFeedEvidence(chainId, manifest) {
    const evidence = manifest.sequencerUptimeFeedEvidence;
    const metadataAddress = manifest.robinhoodSequencerUptimeFeed;
    const metadataSource = manifest.robinhoodSequencerUptimeFeedSource;
    const metadataCodehash = manifest.robinhoodSequencerUptimeFeedCodehash;
    if (
        !evidence ||
        !/^0x[0-9a-f]{40}$/iu.test(metadataAddress ?? "") ||
        typeof metadataSource !== "string" ||
        metadataSource.trim().length === 0 ||
        !/^0x[0-9a-f]{64}$/iu.test(metadataCodehash ?? "") ||
        evidence.address?.toLowerCase() !== metadataAddress.toLowerCase() ||
        evidence.source !== metadataSource ||
        evidence.runtimeCodehash?.toLowerCase() !==
            metadataCodehash.toLowerCase()
    ) {
        throw new Error(
            `Deployment ${chainId} has incomplete sequencer uptime feed evidence`,
        );
    }

    const zeroAddress = /^0x0{40}$/iu.test(evidence.address);
    if (String(chainId) === "4663") {
        if (
            evidence.mode !== "configured" ||
            zeroAddress ||
            evidence.runtimeCodehash.toLowerCase() === ZERO_CODEHASH ||
            !/^0x[0-9a-f]{64}$/iu.test(evidence.reviewedCodehashPin ?? "") ||
            evidence.reviewedCodehashPin.toLowerCase() !==
                evidence.runtimeCodehash.toLowerCase()
        ) {
            throw new Error(
                "Robinhood mainnet requires a configured, reviewed sequencer uptime feed",
            );
        }
        return;
    }

    if (evidence.mode === "configured") {
        if (
            zeroAddress ||
            evidence.runtimeCodehash.toLowerCase() === ZERO_CODEHASH ||
            evidence.reviewedCodehashPin !== null
        ) {
            throw new Error(
                "Robinhood testnet configured sequencer evidence is invalid",
            );
        }
        return;
    }
    if (
        evidence.mode !== "robinhood-testnet-exception" ||
        !zeroAddress ||
        evidence.runtimeCodehash.toLowerCase() !== ZERO_CODEHASH ||
        evidence.reviewedCodehashPin !== null ||
        !TESTNET_SEQUENCER_EXCEPTION_SOURCES.has(evidence.source)
    ) {
        throw new Error(
            "Robinhood testnet sequencer exception evidence is invalid",
        );
    }
}

function validatePythSequencerUptimeGuardEvidence(chainId, manifest) {
    const policy = pythSequencerPolicyForChain(chainId);
    const evidence = manifest.pythSequencerUptimeGuardEvidence;
    const expectedKeys = [
        "erc4626Required",
        "feed",
        "mode",
        "primaryOracle",
        "primaryOracleRequired",
        "runtimeCodehash",
        "source",
    ];
    if (
        !evidence ||
        Object.keys(evidence).sort().join(",") !== expectedKeys.join(",") ||
        !/^0x[0-9a-f]{40}$/iu.test(evidence.feed ?? "") ||
        evidence.feed.toLowerCase() !== policy.feed.toLowerCase() ||
        evidence.mode !== policy.mode ||
        evidence.source !== policy.source ||
        evidence.primaryOracle !== "PythOracle" ||
        evidence.primaryOracleRequired !== policy.required ||
        evidence.erc4626Required !== policy.required ||
        !/^0x[0-9a-f]{64}$/iu.test(evidence.runtimeCodehash ?? "") ||
        (policy.feed === "0x0000000000000000000000000000000000000000"
            ? evidence.runtimeCodehash.toLowerCase() !== ZERO_CODEHASH
            : evidence.runtimeCodehash.toLowerCase() === ZERO_CODEHASH)
    ) {
        throw new Error(
            `Deployment ${chainId} has incomplete Pyth sequencer uptime guard evidence`,
        );
    }
}

function isPublicChain(chainId) {
    const normalizedChainId = normalizeChainId(chainId);
    return normalizedChainId !== null && !isLocalChain(normalizedChainId);
}

function requirePromotedManifestForPublicTarget(chainId, deployments) {
    const normalizedChainId = normalizeChainId(chainId);
    if (!isPublicChain(normalizedChainId)) return null;

    const manifest = deployments?.[normalizedChainId];
    if (!manifest) {
        throw new Error(
            `Deployment ${normalizedChainId} has no promoted active manifest; raw broadcasts remain quarantined`,
        );
    }

    return validateActiveDeploymentManifest(normalizedChainId, manifest);
}

function constrainPublicChainContracts(allGeneratedContracts, deployments) {
    const constrainedContracts = {};

    for (const [chainId, chainContracts] of Object.entries(
        allGeneratedContracts,
    )) {
        if (!isPublicChain(chainId)) {
            constrainedContracts[chainId] = { ...chainContracts };
            continue;
        }

        const manifest = deployments?.[chainId];
        if (!manifest) {
            continue;
        }
        validateActiveDeploymentManifest(chainId, manifest);

        const manifestAddressByName = new Map(
            Object.entries(manifest)
                .filter(
                    ([address, name]) =>
                        isAddressKey(address) && typeof name === "string",
                )
                .map(([address, name]) => [name, address]),
        );
        const permittedContracts = {};

        for (const [contractName, contractData] of Object.entries(
            chainContracts,
        )) {
            const manifestAddress = manifestAddressByName.get(contractName);
            if (
                !manifestAddress ||
                typeof contractData?.address !== "string" ||
                contractData.address.toLowerCase() !==
                    manifestAddress.toLowerCase()
            ) {
                continue;
            }

            permittedContracts[contractName] = {
                ...contractData,
                address: manifestAddress,
            };
        }

        if (Object.keys(permittedContracts).length > 0) {
            constrainedContracts[chainId] = permittedContracts;
        }
    }

    return constrainedContracts;
}

function remapContractNamesByManifest(chainContracts, manifest) {
    const remappedContracts = {};

    for (const [contractName, contractData] of Object.entries(chainContracts)) {
        const manifestName = deploymentJsonNameForAddress(
            manifest,
            contractData.address,
        );
        remappedContracts[manifestName || contractName] = contractData;
    }

    return remappedContracts;
}

function validateActiveDeploymentManifest(chainId, manifest) {
    const normalizedChainId = normalizeChainId(chainId);
    if (!isPublicChain(normalizedChainId)) {
        return manifest;
    }

    if (
        String(manifest?.schemaVersion) !== "2" ||
        manifest?.status !== "active" ||
        String(manifest?.chainId) !== normalizedChainId
    ) {
        throw new Error(
            `Deployment ${normalizedChainId} is not a promoted schema-v2 active manifest`,
        );
    }

    for (const field of [
        "deploymentId",
        "configurationDigest",
        "validatedAt",
    ]) {
        if (
            typeof manifest[field] !== "string" ||
            manifest[field].length === 0
        ) {
            throw new Error(
                `Deployment ${normalizedChainId} is missing ${field} evidence`,
            );
        }
    }
    const finalityEvidence = manifest.finalityEvidence;
    const rpcProviderOperators = finalityEvidence?.rpcProviderOperators;
    let normalizedRpcProviderOperators;
    try {
        normalizedRpcProviderOperators = requireIndependentRpcOperators(
            rpcProviderOperators?.deployment,
            rpcProviderOperators?.validation,
        );
    } catch {
        normalizedRpcProviderOperators = null;
    }
    if (
        finalityEvidence?.blockTag !== "finalized" ||
        finalityEvidence?.independentValidationRpc !== true ||
        finalityEvidence?.policySchemaVersion !== 2 ||
        !/^(?:0|[1-9][0-9]*)$/u.test(finalityEvidence?.blockNumber ?? "") ||
        !/^0x[0-9a-f]{64}$/iu.test(finalityEvidence?.blockHash ?? "") ||
        !normalizedRpcProviderOperators ||
        Object.keys(rpcProviderOperators).sort().join(",") !==
            "deployment,validation" ||
        rpcProviderOperators.deployment !==
            normalizedRpcProviderOperators.deployment ||
        rpcProviderOperators.validation !==
            normalizedRpcProviderOperators.validation
    ) {
        throw new Error(
            `Deployment ${normalizedChainId} is missing finalized-state promotion evidence`,
        );
    }
    const evidenceObjects = [
        manifest.codehashEvidence,
        manifest.addressEvidence,
        manifest.reviewedCodehashPins,
    ];
    if (
        !Array.isArray(manifest.transactionHashes) ||
        manifest.transactionHashes.length === 0 ||
        evidenceObjects.some(
            (value) =>
                value === null ||
                typeof value !== "object" ||
                Array.isArray(value),
        )
    ) {
        throw new Error(
            `Deployment ${normalizedChainId} is missing promotion evidence`,
        );
    }

    const addressEntries = Object.entries(manifest).filter(
        ([key, value]) => isAddressKey(key) && typeof value === "string",
    );
    const addressNames = addressEntries.map(([, value]) => value).sort();
    const hasPyth = addressNames.includes("PythOracle");
    const hasChainlink = addressNames.includes("ChainlinkOracleFeed");
    if (hasPyth === hasChainlink) {
        throw new Error(
            `Deployment ${normalizedChainId} must select exactly one production oracle inventory`,
        );
    }
    if (hasChainlink) {
        validateSequencerUptimeFeedEvidence(normalizedChainId, manifest);
        if (manifest.pythSequencerUptimeGuardEvidence !== undefined) {
            throw new Error(
                `Deployment ${normalizedChainId} has Pyth sequencer evidence without a Pyth deployment`,
            );
        }
    } else {
        if (manifest.sequencerUptimeFeedEvidence !== undefined) {
            throw new Error(
                `Deployment ${normalizedChainId} has Robinhood sequencer evidence without a Chainlink deployment`,
            );
        }
        validatePythSequencerUptimeGuardEvidence(normalizedChainId, manifest);
    }
    const expectedNames = [
        ...(hasPyth ? PYTH_CORE_INVENTORY : CHAINLINK_CORE_INVENTORY),
        ...(manifest.robinhoodDemoAssetsEnabled === "true"
            ? DEMO_EXTRA_INVENTORY
            : []),
    ].sort();
    if (JSON.stringify(addressNames) !== JSON.stringify(expectedNames)) {
        throw new Error(
            `Deployment ${normalizedChainId} does not match the reviewed production inventory`,
        );
    }

    const relaxedRobinhoodTestnet =
        normalizedChainId === "46630" &&
        manifest.productionGuardMode === "relaxed";
    const evidencedAddresses = new Map(
        Object.entries(manifest.codehashEvidence).map(([address, codehash]) => [
            address.toLowerCase(),
            codehash,
        ]),
    );
    const sourcedAddresses = new Map(
        Object.entries(manifest.addressEvidence).map(([address, source]) => [
            address.toLowerCase(),
            source,
        ]),
    );
    for (const [address] of addressEntries) {
        const normalizedAddress = address.toLowerCase();
        const codehash = evidencedAddresses.get(normalizedAddress);
        const source = sourcedAddresses.get(normalizedAddress);
        if (
            !evidencedAddresses.has(normalizedAddress) ||
            !sourcedAddresses.has(normalizedAddress) ||
            (relaxedRobinhoodTestnet &&
                (!/^0x[0-9a-f]{64}$/iu.test(codehash ?? "") ||
                    typeof source !== "string" ||
                    source.trim().length === 0))
        ) {
            throw new Error(
                `Deployment ${normalizedChainId} has incomplete address or codehash evidence`,
            );
        }
    }

    const requiredPins = requiredReviewedCodehashPinNames(
        hasPyth ? "pyth" : "chainlink",
    );
    const addressByName = new Map(
        addressEntries.map(([address, name]) => [name, address]),
    );
    const pinNames = Object.keys(manifest.reviewedCodehashPins).sort();
    const reviewedPinsAreIncomplete =
        JSON.stringify(pinNames) !== JSON.stringify([...requiredPins].sort()) ||
        requiredPins.some((name) => {
            const address = addressByName.get(name);
            return (
                !/^0x[0-9a-f]{64}$/iu.test(
                    manifest.reviewedCodehashPins[name] ?? "",
                ) ||
                manifest.reviewedCodehashPins[name].toLowerCase() !==
                    manifest.codehashEvidence[address]?.toLowerCase()
            );
        });
    if (
        (relaxedRobinhoodTestnet && pinNames.length !== 0) ||
        (!relaxedRobinhoodTestnet && reviewedPinsAreIncomplete)
    ) {
        throw new Error(
            `Deployment ${normalizedChainId} has incomplete reviewed codehash pins`,
        );
    }

    return manifest;
}

function getExplicitTargetChainId() {
    return normalizeChainId(
        process.env.DEPLOY_CHAIN_ID || process.env.CHAIN_ID,
    );
}

function parseTransactionAndReceiptRun(filePath) {
    try {
        const content = readFileSync(filePath, "utf8");
        const broadcastData = JSON.parse(content);
        return {
            transactions: broadcastData.transactions || [],
            receipts: broadcastData.receipts || [],
        };
    } catch (error) {
        console.warn(`Warning: Could not parse ${filePath}:`, error.message);
        return [];
    }
}

function getDeploymentHistory(broadcastPath) {
    const files = getFiles(broadcastPath);
    const deploymentHistory = new Map();

    // Sort files to process them in chronological order
    const runFiles = files
        .filter(
            (file) =>
                file.startsWith("run-") &&
                file.endsWith(".json") &&
                !file.includes("run-latest"),
        )
        .sort((a, b) => {
            // Extract run numbers and compare them
            const runA = parseInt(a.match(/run-(\d+)/)?.[1] || "0");
            const runB = parseInt(b.match(/run-(\d+)/)?.[1] || "0");
            return runA - runB;
        });

    for (const file of runFiles) {
        const { transactions, receipts } = parseTransactionAndReceiptRun(
            join(broadcastPath, file),
        );

        for (const tx of transactions) {
            if (tx.transactionType === "CREATE") {
                // Store or update contract deployment info
                // Use contractName + address as key to handle proxy deployments correctly
                const key = `${tx.contractName}-${tx.contractAddress}`;
                deploymentHistory.set(key, {
                    contractName: tx.contractName,
                    address: tx.contractAddress,
                    deploymentFile: file,
                    transaction: tx,
                    receipt: receipts.find(
                        (r) => r.transactionHash === tx.hash,
                    ),
                });

                // Handle proxy deployments: if this is a proxy, also create entries for contracts in additionalContracts
                if (
                    tx.additionalContracts &&
                    Array.isArray(tx.additionalContracts)
                ) {
                    for (const additionalContract of tx.additionalContracts) {
                        if (additionalContract.name) {
                            // Create entry for the additional contract using the proxy address
                            const additionalKey = `${additionalContract.name}-${tx.contractAddress}`;
                            deploymentHistory.set(additionalKey, {
                                contractName: additionalContract.name,
                                address: tx.contractAddress, // Proxy address
                                deploymentFile: file,
                                transaction: tx,
                                receipt: receipts.find(
                                    (r) => r.transactionHash === tx.hash,
                                ),
                            });
                        }
                    }
                }
            }
        }
    }

    return Array.from(deploymentHistory.values());
}

function getLatestRunDeployments(broadcastPath) {
    const scriptFolders = getDirectories(broadcastPath);
    const latestDeployments = new Map();

    scriptFolders.forEach((scriptFolder) => {
        const scriptPath = join(broadcastPath, scriptFolder);
        const chainFolders = getDirectories(scriptPath);

        chainFolders.forEach((chainId) => {
            const runLatestPath = join(scriptPath, chainId, "run-latest.json");
            if (!existsSync(runLatestPath)) {
                return;
            }

            const { transactions, receipts } =
                parseTransactionAndReceiptRun(runLatestPath);
            const fileTimestamp = statSync(runLatestPath).mtimeMs;

            for (const tx of transactions) {
                if (tx.transactionType !== "CREATE" || !tx.contractName)
                    continue;

                const receipt = receipts.find(
                    (r) => r.transactionHash === tx.hash,
                );
                const baseDeployment = {
                    address: tx.contractAddress,
                    deploymentFile: "run-latest.json",
                    deploymentScript: scriptFolder,
                    deployedOnBlock: receipt?.blockNumber,
                };

                const key = `${chainId}-${tx.contractName}`;
                const current = latestDeployments.get(key);
                if (!current || fileTimestamp >= current.timestamp) {
                    latestDeployments.set(key, {
                        contractName: tx.contractName,
                        chainId,
                        timestamp: fileTimestamp,
                        ...baseDeployment,
                    });
                }

                if (
                    !tx.additionalContracts ||
                    !Array.isArray(tx.additionalContracts)
                ) {
                    continue;
                }

                for (const additionalContract of tx.additionalContracts) {
                    if (!additionalContract.name) continue;

                    const additionalKey = `${chainId}-${additionalContract.name}`;
                    const currentAdditional =
                        latestDeployments.get(additionalKey);
                    if (
                        !currentAdditional ||
                        fileTimestamp >= currentAdditional.timestamp
                    ) {
                        latestDeployments.set(additionalKey, {
                            contractName: additionalContract.name,
                            chainId,
                            timestamp: fileTimestamp,
                            ...baseDeployment,
                        });
                    }
                }
            }
        });
    });

    return Array.from(latestDeployments.values());
}

function getChainActivity(broadcastPath, deploymentsPath) {
    const chainActivity = new Map();

    if (existsSync(deploymentsPath)) {
        for (const fileName of getFiles(deploymentsPath)) {
            if (!fileName.endsWith(".json")) {
                continue;
            }

            const chainId = fileName.replace(/\.json$/, "");
            const mtimeMs = statSync(join(deploymentsPath, fileName)).mtimeMs;
            const current = chainActivity.get(chainId) || 0;
            chainActivity.set(chainId, Math.max(current, mtimeMs));
        }
    }

    for (const scriptFolder of getDirectories(broadcastPath)) {
        const scriptPath = join(broadcastPath, scriptFolder);
        for (const chainId of getDirectories(scriptPath)) {
            const runLatestPath = join(scriptPath, chainId, "run-latest.json");
            if (!existsSync(runLatestPath)) {
                continue;
            }

            const mtimeMs = statSync(runLatestPath).mtimeMs;
            const current = chainActivity.get(chainId) || 0;
            chainActivity.set(chainId, Math.max(current, mtimeMs));
        }
    }

    return chainActivity;
}

function sortChainIdsForSelection(chainIds, chainActivity, explicitChainId) {
    return [...chainIds].sort((a, b) => {
        if (explicitChainId) {
            if (a === explicitChainId) return -1;
            if (b === explicitChainId) return 1;
        }

        const activityDelta =
            (chainActivity.get(b) || 0) - (chainActivity.get(a) || 0);
        if (activityDelta !== 0) {
            return activityDelta;
        }

        if (isLocalChain(a) !== isLocalChain(b)) {
            return isLocalChain(a) ? 1 : -1;
        }

        return a.localeCompare(b);
    });
}

function getArtifactOfContract(contractName) {
    const current_path_to_artifacts = join(
        __dirname,
        "..",
        `out/${contractName}.sol`,
    );

    if (!existsSync(current_path_to_artifacts)) return null;

    const artifactJson = JSON.parse(
        readFileSync(`${current_path_to_artifacts}/${contractName}.json`),
    );

    return artifactJson;
}

function getInheritedFromContracts(artifact) {
    let inheritedFromContracts = [];
    if (artifact?.ast) {
        for (const astNode of artifact.ast.nodes) {
            if (astNode.nodeType == "ContractDefinition") {
                if (astNode.baseContracts.length > 0) {
                    inheritedFromContracts = astNode.baseContracts.map(
                        ({ baseName }) => baseName.name,
                    );
                }
            }
        }
    }
    return inheritedFromContracts;
}

function getInheritedFunctions(mainArtifact) {
    const inheritedFromContracts = getInheritedFromContracts(mainArtifact);
    const inheritedFunctions = {};
    for (const inheritanceContractName of inheritedFromContracts) {
        const artifact = getArtifactOfContract(inheritanceContractName);
        if (artifact) {
            const {
                abi,
                ast: { absolutePath },
            } = artifact;
            for (const abiEntry of abi) {
                if (abiEntry.type == "function") {
                    inheritedFunctions[abiEntry.name] = absolutePath;
                }
            }
        }
    }
    return inheritedFunctions;
}

function isLocalChain(chainId) {
    return LOCAL_CHAIN_IDS.has(normalizeChainId(chainId));
}

function isLocalOnlyContract(contractName) {
    return (
        contractName.startsWith("Mock") ||
        contractName === "AccessControlExample"
    );
}

function processAllDeployments(broadcastPath) {
    const scriptFolders = getDirectories(broadcastPath);
    const allDeployments = new Map();

    scriptFolders.forEach((scriptFolder) => {
        const scriptPath = join(broadcastPath, scriptFolder);
        const chainFolders = getDirectories(scriptPath);

        chainFolders.forEach((chainId) => {
            const chainPath = join(scriptPath, chainId);
            const deploymentHistory = getDeploymentHistory(chainPath);

            deploymentHistory.forEach((deployment) => {
                const timestamp = parseInt(
                    deployment.deploymentFile.match(/run-(\d+)/)?.[1] || "0",
                );
                const key = `${chainId}-${deployment.contractName}`;

                // Only update if this deployment is newer
                if (
                    !allDeployments.has(key) ||
                    timestamp > allDeployments.get(key).timestamp
                ) {
                    allDeployments.set(key, {
                        ...deployment,
                        timestamp,
                        chainId,
                        deploymentScript: scriptFolder,
                        deployedOnBlock: deployment?.receipt?.blockNumber,
                    });
                }
            });
        });
    });

    const allContracts = {};

    allDeployments.forEach((deployment) => {
        const { chainId, contractName } = deployment;
        const artifact = getArtifactOfContract(contractName);

        if (artifact) {
            if (!isLocalChain(chainId) && isLocalOnlyContract(contractName)) {
                return;
            }

            if (!allContracts[chainId]) {
                allContracts[chainId] = {};
            }

            allContracts[chainId][contractName] = {
                address: deployment.address,
                abi: artifact.abi,
                inheritedFunctions: getInheritedFunctions(artifact),
                deploymentFile: deployment.deploymentFile,
                deploymentScript: deployment.deploymentScript,
                deployedOnBlock:
                    deployment?.deployedOnBlock &&
                    Number(BigInt(deployment.deployedOnBlock)),
            };
        }
    });

    return allContracts;
}

function updatePonderConfig(
    factoryAddress,
    governorAddress,
    governorBlock,
    chainId = "31337",
) {
    const PONDER_CONFIG_PATH = join(
        __dirname,
        "..",
        "..",
        "ponder",
        "ponder.config.ts",
    );

    if (!existsSync(PONDER_CONFIG_PATH)) {
        console.warn(
            `⚠️  Ponder config not found at ${PONDER_CONFIG_PATH}, skipping update`,
        );
        return;
    }

    let configContent = readFileSync(PONDER_CONFIG_PATH, "utf8");

    // Update the factory address in the default value
    // This regex matches: const factoryAddress = (process.env.PONDER_FACTORY_ADDRESS || "0x...") as `0x${string}`;
    const factoryAddressRegex =
        /(const factoryAddress = \(\s*process\.env\.PONDER_FACTORY_ADDRESS\s*\|\|\s*")(0x[a-fA-F0-9]+)("\s*\) as `0x\$\{string\}`;)/s;

    if (factoryAddress && factoryAddressRegex.test(configContent)) {
        configContent = configContent.replace(
            factoryAddressRegex,
            `$1${factoryAddress}$3`,
        );
        console.log(
            `📝 Updated Ponder config with factory address: ${factoryAddress}`,
        );
    } else if (factoryAddress) {
        console.log(
            `📝 Ponder factory address is env-driven; skipping hardcoded config replacement`,
        );
    }

    // Update the YSGovernor address in the default value
    // This regex matches: address: (process.env.PONDER_GOVERNOR_ADDRESS || "0x...") as `0x${string}`,
    const governorAddressRegex =
        /(address: \(\s*process\.env\.PONDER_GOVERNOR_ADDRESS\s*\|\|\s*")(0x[a-fA-F0-9]+)("\s*\) as `0x\$\{string\}`)/s;

    if (governorAddress && governorAddressRegex.test(configContent)) {
        configContent = configContent.replace(
            governorAddressRegex,
            `$1${governorAddress}$3`,
        );
        console.log(
            `📝 Updated Ponder config with YSGovernor address: ${governorAddress}`,
        );
    } else if (governorAddress) {
        console.log(
            `📝 Ponder YSGovernor address is env-driven; skipping hardcoded config replacement`,
        );
    }

    // Update the YSGovernor startBlock
    // This regex matches: startBlock: 123456, // YSGovernor deployed at block 123458, start slightly before
    if (governorBlock) {
        const startBlock = Math.max(0, governorBlock - 4); // Start 4 blocks before deployment
        // Match: startBlock: 123456, // YSGovernor deployed at block 123458, start slightly before
        const startBlockRegex =
            /(startBlock: )(\d+)(, \/\/ YSGovernor deployed at block )(\d+)(, start slightly before)/;

        if (startBlockRegex.test(configContent)) {
            configContent = configContent.replace(
                startBlockRegex,
                `$1${startBlock}$3${governorBlock}$5`,
            );
            console.log(
                `📝 Updated Ponder config with YSGovernor startBlock: ${startBlock} (deployed at block ${governorBlock})`,
            );
        } else {
            // Try a simpler pattern if the comment format doesn't match
            const simpleStartBlockRegex =
                /(YSGovernor:[\s\S]*?startBlock: )(\d+)/;
            if (simpleStartBlockRegex.test(configContent)) {
                configContent = configContent.replace(
                    simpleStartBlockRegex,
                    `$1${startBlock}`,
                );
                console.log(
                    `📝 Updated Ponder config with YSGovernor startBlock: ${startBlock}`,
                );
            }
        }
    }

    if (factoryAddress || governorAddress) {
        writeFileSync(PONDER_CONFIG_PATH, configContent, "utf8");
    }
}

function isAddressKey(value) {
    return typeof value === "string" && value.startsWith("0x");
}

function deploymentJsonAddressFor(deploymentData, contractName) {
    if (!deploymentData) return null;

    let address = null;
    for (const [key, value] of Object.entries(deploymentData)) {
        if (isAddressKey(key) && value === contractName) {
            address = key;
        }
    }

    return address;
}

function deploymentJsonNameForAddress(deploymentData, address) {
    if (!deploymentData || !address) return null;

    const normalizedAddress = address.toLowerCase();
    for (const [key, value] of Object.entries(deploymentData)) {
        if (!isAddressKey(key)) continue;
        if (
            key.toLowerCase() === normalizedAddress &&
            typeof value === "string"
        ) {
            return value;
        }
    }

    return null;
}

function generatedContractAddressFor(chainContracts, contractName) {
    return chainContracts?.[contractName]?.address || null;
}

function generatedContractBlockFor(chainContracts, contractName) {
    return chainContracts?.[contractName]?.deployedOnBlock;
}

function selectPonderDeployment(chainIds, allGeneratedContracts, deployments) {
    for (const chainId of chainIds) {
        const chainContracts = allGeneratedContracts[chainId] || {};
        const promotedManifest = isPublicChain(chainId)
            ? deployments?.[chainId]
            : null;
        if (isPublicChain(chainId) && !promotedManifest) {
            continue;
        }
        if (promotedManifest) {
            validateActiveDeploymentManifest(chainId, promotedManifest);
        }
        const generatedFactoryAddress = generatedContractAddressFor(
            chainContracts,
            "SplitRiskPoolFactory",
        );
        const generatedGovernorAddress = generatedContractAddressFor(
            chainContracts,
            "YSGovernor",
        );
        const manifestFactoryAddress = deploymentJsonAddressFor(
            deployments[chainId],
            "SplitRiskPoolFactory",
        );
        const manifestGovernorAddress = deploymentJsonAddressFor(
            deployments[chainId],
            "YSGovernor",
        );
        if (
            promotedManifest &&
            (generatedFactoryAddress?.toLowerCase() !==
                manifestFactoryAddress?.toLowerCase() ||
                generatedGovernorAddress?.toLowerCase() !==
                    manifestGovernorAddress?.toLowerCase())
        ) {
            continue;
        }
        const factoryAddress =
            generatedFactoryAddress || manifestFactoryAddress;
        const governorAddress =
            generatedGovernorAddress || manifestGovernorAddress;

        if (!factoryAddress || !governorAddress) {
            continue;
        }

        return {
            chainId,
            factoryAddress,
            governorAddress,
            governorBlock: generatedContractBlockFor(
                chainContracts,
                "YSGovernor",
            ),
        };
    }

    return null;
}

async function main() {
    const current_path_to_broadcast = join(__dirname, "..", "broadcast");
    const current_path_to_deployments = join(__dirname, "..", "deployments");
    const explicitTargetChainId = getExplicitTargetChainId();
    const chainActivity = getChainActivity(
        current_path_to_broadcast,
        current_path_to_deployments,
    );

    const Deploymentchains = getFiles(current_path_to_deployments);
    const deployments = {};

    // Load existing deployments from deployments directory
    Deploymentchains.forEach((chain) => {
        if (!chain.endsWith(".json")) return;
        chain = chain.slice(0, -5);
        var deploymentObject = JSON.parse(
            readFileSync(`${current_path_to_deployments}/${chain}.json`),
        );
        deployments[chain] = validateActiveDeploymentManifest(
            chain,
            deploymentObject,
        );
    });

    // Process all deployments from all script folders
    let allGeneratedContracts = processAllDeployments(
        current_path_to_broadcast,
    );
    const latestRunDeployments = getLatestRunDeployments(
        current_path_to_broadcast,
    );

    latestRunDeployments.forEach((deployment) => {
        const { chainId, contractName } = deployment;
        const artifact = getArtifactOfContract(contractName);

        if (!artifact) return;
        if (!isLocalChain(chainId) && isLocalOnlyContract(contractName)) {
            return;
        }

        if (!allGeneratedContracts[chainId]) {
            allGeneratedContracts[chainId] = {};
        }

        allGeneratedContracts[chainId][contractName] = {
            address: deployment.address,
            abi: artifact.abi,
            inheritedFunctions: getInheritedFunctions(artifact),
            deploymentFile: deployment.deploymentFile,
            deploymentScript: deployment.deploymentScript,
            deployedOnBlock:
                deployment?.deployedOnBlock &&
                Number(BigInt(deployment.deployedOnBlock)),
        };
    });

    requirePromotedManifestForPublicTarget(explicitTargetChainId, deployments);
    // Update contract keys based on deployments if they exist
    Object.entries(allGeneratedContracts).forEach(([chainId, contracts]) => {
        allGeneratedContracts[chainId] = remapContractNamesByManifest(
            contracts,
            deployments[chainId],
        );
        Object.entries(allGeneratedContracts[chainId]).forEach(
            ([contractName, contractData]) => {
                const artifact = getArtifactOfContract(contractName);
                if (artifact) {
                    allGeneratedContracts[chainId][contractName] = {
                        ...contractData,
                        abi: artifact.abi,
                        inheritedFunctions: getInheritedFunctions(artifact),
                    };
                }
            },
        );

        // Also update deployment-mapped contract addresses from deployments JSON.
        // This keeps local generated addresses aligned with the latest deploy entrypoint.
        if (deployments[chainId] && isLocalChain(chainId)) {
            for (const [address, name] of Object.entries(
                deployments[chainId],
            )) {
                if (!isAddressKey(address)) continue;
                if (typeof name !== "string") continue;

                if (allGeneratedContracts[chainId][name]) {
                    allGeneratedContracts[chainId][name].address = address;
                }
            }
        }
    });

    allGeneratedContracts = constrainPublicChainContracts(
        allGeneratedContracts,
        deployments,
    );

    const NEXTJS_TARGET_DIR = "../nextjs/contracts/";

    // Ensure target directories exist
    if (!existsSync(NEXTJS_TARGET_DIR)) {
        mkdirSync(NEXTJS_TARGET_DIR, { recursive: true });
    }

    // Generate the deployedContracts content
    const fileContent = Object.entries(allGeneratedContracts).reduce(
        (content, [chainId, chainConfig]) => {
            const cleanedChainConfig = Object.fromEntries(
                Object.entries(chainConfig).map(
                    ([contractName, contractData]) => {
                        const { deploymentFile, deploymentScript, ...rest } =
                            contractData;
                        return [contractName, rest];
                    },
                ),
            );
            return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(
                cleanedChainConfig,
                null,
                2,
            )},`;
        },
        "",
    );

    // Write the files
    const fileTemplate = (importPath) => `
    ${generatedContractComment}
    import type { GenericContractsDeclaration } from "${importPath}";

    const deployedContracts = {${fileContent}} as const;

    export default deployedContracts satisfies GenericContractsDeclaration;
  `;

    writeFileSync(
        `${NEXTJS_TARGET_DIR}deployedContracts.ts`,
        await format(fileTemplate("~~/utils/scaffold-eth/contract"), {
            parser: "typescript",
        }),
    );

    console.log(
        `📝 Updated TypeScript contract definition file on ${NEXTJS_TARGET_DIR}deployedContracts.ts`,
    );

    // Update ponder.config.ts with the chain that was just deployed, or the
    // most recently updated non-local deployment when no explicit target exists.
    const chainIds = sortChainIdsForSelection(
        Object.keys(allGeneratedContracts),
        chainActivity,
        explicitTargetChainId,
    );

    const ponderDeployment = selectPonderDeployment(
        chainIds,
        allGeneratedContracts,
        deployments,
    );

    if (ponderDeployment) {
        updatePonderConfig(
            ponderDeployment.factoryAddress,
            ponderDeployment.governorAddress,
            ponderDeployment.governorBlock,
            ponderDeployment.chainId,
        );
        console.log(
            `✅ Updated Ponder config with chain ${ponderDeployment.chainId} factory address: ${ponderDeployment.factoryAddress}`,
        );
        console.log(
            `✅ Updated Ponder config with chain ${ponderDeployment.chainId} YSGovernor address: ${
                ponderDeployment.governorAddress
            }${ponderDeployment.governorBlock ? ` (block ${ponderDeployment.governorBlock})` : ""}`,
        );
    } else {
        console.warn(
            `⚠️  SplitRiskPoolFactory and YSGovernor not found on the same deployment chain`,
        );
    }
}

if (process.argv[1] === __filename) {
    main().catch((error) => {
        console.error("Error:", error);
        process.exitCode = 1;
    });
}

export {
    CHAINLINK_CORE_INVENTORY,
    PYTH_CORE_INVENTORY,
    constrainPublicChainContracts,
    deploymentJsonNameForAddress,
    remapContractNamesByManifest,
    requirePromotedManifestForPublicTarget,
    requiredReviewedCodehashPinNames,
    selectPonderDeployment,
    sortChainIdsForSelection,
    validateActiveDeploymentManifest,
};
