// Generated by scripts/generate-evm-abis.mjs from SplitRiskPool.sol/SplitRiskPool.json — do not edit by hand.
export const splitRiskPoolAbi = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "fallback",
    stateMutability: "nonpayable",
  },
  {
    type: "receive",
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "BACKING_TOKEN",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "COLLATERAL_RATIO",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "COMMISSION_RATE",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "POOL_CREATOR",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "POOL_FACTORY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "POOL_FEE",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SHIELDED_TOKEN",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "UPGRADE_INTERFACE_VERSION",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "acceptGovernanceTimelock",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptGovernanceTimelockFromFactory",
    inputs: [
      {
        name: "expectedGovernanceTimelock",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "accessControl",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accessControlCanGateWithdrawals",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accumulatedCommissions",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accumulatedPoolFee",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accumulatedProtocolFee",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "backingTokenDecimals",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "backingTokenScale",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelGovernanceTimelockFromFactory",
    inputs: [
      {
        name: "expectedGovernanceTimelock",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelGovernanceTimelockTransfer",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelUnlockProcess",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimCommission",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimExpiredProtectorBacking",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minAmountOut",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "received",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRewards",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "commissionsClaimed",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentEpochCommissionReserve",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "depositBackingAsset",
    inputs: [
      {
        name: "asset",
        type: "address",
        internalType: "address",
      },
      {
        name: "depositAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minReceivedAmount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "depositShieldedAsset",
    inputs: [
      {
        name: "asset",
        type: "address",
        internalType: "address",
      },
      {
        name: "depositAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minReceivedAmount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "feeValueBaselineUsd",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "forfeitCommission",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAccessControlStatus",
    inputs: [],
    outputs: [
      {
        name: "activeAccessControl",
        type: "address",
        internalType: "address",
      },
      {
        name: "depositsGated",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "withdrawalsGated",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "governanceInstalled",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAvailableForWithdrawal",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getClaimableCommission",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getExpiredProtectorBackingClaim",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLockedAmount",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOracleInfo",
    inputs: [],
    outputs: [
      {
        name: "oracle",
        type: "address",
        internalType: "address",
      },
      {
        name: "isDualOracle",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "primaryFeed",
        type: "address",
        internalType: "address",
      },
      {
        name: "backupFeed",
        type: "address",
        internalType: "address",
      },
      {
        name: "isBackupActive",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPoolBalances",
    inputs: [],
    outputs: [
      {
        name: "shieldedTokenPoolBalance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "totalBackingTokenPoolBalance",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProtectorDepositInfo",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "depositTime",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "unlockRequestTime",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "lockedAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "availableAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "claimableCommission",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProtectorPositionAmount",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getReservedFees",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getShieldDepositInfo",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "depositTime",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "valueAtDeposit",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "lastFeeClaimTime",
        type: "uint64",
        internalType: "uint64",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserNFTCounts",
    inputs: [
      {
        name: "user",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "shieldNFTCount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "protectorNFTCount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUtilizationRatio",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUtilizationRatioUsd",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getWithdrawableBalance",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "governanceAccessControlInstalled",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "governanceTimelock",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasEverLaunched",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "historicalCommissionReserve",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      {
        name: "_shieldedTokenInfo",
        type: "tuple",
        internalType: "struct TokenWhitelistLib.TokenInfo",
        components: [
          {
            name: "name",
            type: "string",
            internalType: "string",
          },
          {
            name: "symbol",
            type: "string",
            internalType: "string",
          },
          {
            name: "token",
            type: "address",
            internalType: "address",
          },
          {
            name: "primaryOracleFeed",
            type: "address",
            internalType: "address",
          },
          {
            name: "backupOracleFeed",
            type: "address",
            internalType: "address",
          },
          {
            name: "minCollateralRatioBp",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
      {
        name: "_backingTokenInfo",
        type: "tuple",
        internalType: "struct TokenWhitelistLib.TokenInfo",
        components: [
          {
            name: "name",
            type: "string",
            internalType: "string",
          },
          {
            name: "symbol",
            type: "string",
            internalType: "string",
          },
          {
            name: "token",
            type: "address",
            internalType: "address",
          },
          {
            name: "primaryOracleFeed",
            type: "address",
            internalType: "address",
          },
          {
            name: "backupOracleFeed",
            type: "address",
            internalType: "address",
          },
          {
            name: "minCollateralRatioBp",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
      {
        name: "_commissionRate",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_poolFee",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_poolCreator",
        type: "address",
        internalType: "address",
      },
      {
        name: "_collateralRatio",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_governanceTimelock",
        type: "address",
        internalType: "address",
      },
      {
        name: "_priceOracle",
        type: "address",
        internalType: "address",
      },
      {
        name: "_protocolFeeRecipient",
        type: "address",
        internalType: "address",
      },
      {
        name: "_shieldReceiptNFT",
        type: "address",
        internalType: "address",
      },
      {
        name: "_protectorReceiptNFT",
        type: "address",
        internalType: "address",
      },
      {
        name: "initialOwner",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initializeWithAccessControl",
    inputs: [
      {
        name: "_shieldedTokenInfo",
        type: "tuple",
        internalType: "struct TokenWhitelistLib.TokenInfo",
        components: [
          {
            name: "name",
            type: "string",
            internalType: "string",
          },
          {
            name: "symbol",
            type: "string",
            internalType: "string",
          },
          {
            name: "token",
            type: "address",
            internalType: "address",
          },
          {
            name: "primaryOracleFeed",
            type: "address",
            internalType: "address",
          },
          {
            name: "backupOracleFeed",
            type: "address",
            internalType: "address",
          },
          {
            name: "minCollateralRatioBp",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
      {
        name: "_backingTokenInfo",
        type: "tuple",
        internalType: "struct TokenWhitelistLib.TokenInfo",
        components: [
          {
            name: "name",
            type: "string",
            internalType: "string",
          },
          {
            name: "symbol",
            type: "string",
            internalType: "string",
          },
          {
            name: "token",
            type: "address",
            internalType: "address",
          },
          {
            name: "primaryOracleFeed",
            type: "address",
            internalType: "address",
          },
          {
            name: "backupOracleFeed",
            type: "address",
            internalType: "address",
          },
          {
            name: "minCollateralRatioBp",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
      {
        name: "_commissionRate",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_poolFee",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_poolCreator",
        type: "address",
        internalType: "address",
      },
      {
        name: "_collateralRatio",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_governanceTimelock",
        type: "address",
        internalType: "address",
      },
      {
        name: "_priceOracle",
        type: "address",
        internalType: "address",
      },
      {
        name: "_protocolFeeRecipient",
        type: "address",
        internalType: "address",
      },
      {
        name: "_shieldReceiptNFT",
        type: "address",
        internalType: "address",
      },
      {
        name: "_protectorReceiptNFT",
        type: "address",
        internalType: "address",
      },
      {
        name: "initialOwner",
        type: "address",
        internalType: "address",
      },
      {
        name: "initialAccessControl",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isAssetSupported",
    inputs: [
      {
        name: "asset",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "supported",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastClaimRewardsTime",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "partialWithdrawShielded",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "withdrawAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "preferredAsset",
        type: "address",
        internalType: "address",
      },
      {
        name: "minAmountOut",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "newTokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pauseFromFactory",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "payPoolFee",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "payProtocolFee",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pendingGovernanceTimelock",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingProtectorRewardDust",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolConfig",
    inputs: [],
    outputs: [
      {
        name: "shieldedMinDepositAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "shieldedMaxDepositAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "backingMinDepositAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "backingMaxDepositAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxTotalValueLockedUsd",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minimumPoolTime",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "unlockDuration",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "protocolFeeRecipient",
        type: "address",
        internalType: "address",
      },
      {
        name: "protocolFee",
        type: "uint96",
        internalType: "uint96",
      },
      {
        name: "priceOracle",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolFeeRecipient",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolState",
    inputs: [],
    outputs: [
      {
        name: "shieldedTokenBalance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "totalBackingTokenBalance",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorEpochBackingPositionSettled",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorEpochBackingRemainingReserve",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorEpochBackingRemainingShares",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorEpochFinalRewardPerShare",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorEpochPositionSettled",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorEpochRemainingReserve",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorEpochRemainingShares",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorReceiptNFT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorShareEpoch",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorShareEpochs",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorShares",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protectorWithdraw",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "preferredAsset",
        type: "address",
        internalType: "address",
      },
      {
        name: "minAmountOut",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "proxiableUUID",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "refreshStrictProtectedBackingPriceFlag",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requiresStrictProtectedBackingPrice",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resetShieldedTokenTransferIntegrity",
    inputs: [
      {
        name: "probeAmount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rewardDebt",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rewardPerShareAccumulated",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setAccessControl",
    inputs: [
      {
        name: "newAccessControl",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGovernanceTimelock",
    inputs: [
      {
        name: "newGovernanceTimelock",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGovernanceTimelockFromFactory",
    inputs: [
      {
        name: "newGovernanceTimelock",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPoolFeeRecipient",
    inputs: [
      {
        name: "newRecipient",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setProtectorTransferLockPeriod",
    inputs: [
      {
        name: "newPeriod",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setShieldTransferLockPeriod",
    inputs: [
      {
        name: "newPeriod",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleExpiredProtectorBacking",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minAmountOut",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "received",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleExpiredProtectorPosition",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "shieldReceiptNFT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "shieldedTokenDecimals",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "shieldedTokenScale",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "shieldedTokenTransferIntegrityBroken",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "shieldedTransferIntegrityProbe",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract TransferIntegrityProbe",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "shieldedWithdraw",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "preferredAsset",
        type: "address",
        internalType: "address",
      },
      {
        name: "minAmountOut",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "startUnlockProcess",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sweepInactiveProtectorBackingDustFromFactory",
    inputs: [],
    outputs: [
      {
        name: "sweptAmount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sweepUnaccountedSurplusFromFactory",
    inputs: [],
    outputs: [
      {
        name: "shieldedSweptAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "backingSweptAmount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "totalCommissionsEverAccumulated",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalProtectorShares",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalProtectorTokens",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalShieldCollateralAmount",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalShieldedTokens",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalValueAtDeposit",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [
      {
        name: "newOwner",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePoolConfig",
    inputs: [
      {
        name: "newShieldedMinDepositAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "newShieldedMaxDepositAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "newBackingMinDepositAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "newBackingMaxDepositAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "newMaxTotalValueLockedUsd",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "newMinimumPoolTime",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "newUnlockDuration",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "newProtocolFee",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "newProtocolFeeRecipient",
        type: "address",
        internalType: "address",
      },
      {
        name: "newPriceOracle",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "upgradeToAndCall",
    inputs: [
      {
        name: "newImplementation",
        type: "address",
        internalType: "address",
      },
      {
        name: "data",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "event",
    name: "AccessControlStatusUpdated",
    inputs: [
      {
        name: "accessControl",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "depositsGated",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "withdrawalsGated",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "governanceInstalled",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AccessControlUpdated",
    inputs: [
      {
        name: "previousAccessControl",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newAccessControl",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CommissionClaimed",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CommissionForfeited",
    inputs: [
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeeDropped",
    inputs: [
      {
        name: "feeType",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "droppedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "currentAccumulated",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GovernanceTimelockTransferCancelled",
    inputs: [
      {
        name: "currentGovernance",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "cancelledGovernance",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GovernanceTimelockTransferStarted",
    inputs: [
      {
        name: "currentGovernance",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "pendingGovernance",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GovernanceTimelockUpdated",
    inputs: [
      {
        name: "previousGovernance",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newGovernance",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        name: "version",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NoCommissionToClaim",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ParameterUpdated",
    inputs: [
      {
        name: "parameterName",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "newValue",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PartialWithdrawal",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "oldTokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "newTokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "withdrawAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "remainingAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PoolConfigUpdated",
    inputs: [
      {
        name: "shieldedMinDepositAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "shieldedMaxDepositAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "backingMinDepositAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "backingMaxDepositAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxTotalValueLockedUsd",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "minimumPoolTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "unlockDuration",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "protocolFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "protocolFeeRecipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "priceOracle",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PoolFeePaid",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PoolFeeRecipientUpdated",
    inputs: [
      {
        name: "oldRecipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "newRecipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PoolUnaccountedSurplusSwept",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "nominalAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "receivedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtectorAssetDeposited",
    inputs: [
      {
        name: "depositor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "receiptTokenId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtectorAssetWithdrawn",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "assets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "shares",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtectorResidualBackingReserved",
    inputs: [
      {
        name: "epoch",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtectorResidualBackingSwept",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolFeePaid",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolFeeRecipientUpdated",
    inputs: [
      {
        name: "oldRecipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "newRecipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RewardsClaimed",
    inputs: [
      {
        name: "shieldedAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "feesCharged",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ShieldActivated",
    inputs: [
      {
        name: "withdrawer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "shieldedTokenAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "backingTokenAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ShieldedAssetDeposited",
    inputs: [
      {
        name: "depositor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "receiptTokenId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ShieldedTokenTransferIntegrityBroken",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "nominalAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "receivedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ShieldedTokenTransferIntegrityRestored",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "probeAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ShieldedWithdrawal",
    inputs: [
      {
        name: "withdrawer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "preferredAsset",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StrictPricingProbeFailed",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "factory",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UnlockProcessCancelled",
    inputs: [
      {
        name: "protector",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UnlockProcessStarted",
    inputs: [
      {
        name: "protector",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Upgraded",
    inputs: [
      {
        name: "implementation",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AccessControlDenied",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "operation",
        type: "string",
        internalType: "string",
      },
    ],
  },
  {
    type: "error",
    name: "AccountedBalanceExceedsTokenBalance",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "accountedBalance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "actualBalance",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "AddressEmptyCode",
    inputs: [
      {
        name: "target",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ClaimRewardsCooldownNotMet",
    inputs: [
      {
        name: "availableAt",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "DecimalNormalizationOverflow",
    inputs: [
      {
        name: "price",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "fromDecimals",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "toDecimals",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "DepositAmountTooLarge",
    inputs: [],
  },
  {
    type: "error",
    name: "ERC1967InvalidImplementation",
    inputs: [
      {
        name: "implementation",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ERC1967NonPayable",
    inputs: [],
  },
  {
    type: "error",
    name: "ERC4626BackingOracleUnsupported",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "oracleFeed",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "EnforcedPause",
    inputs: [],
  },
  {
    type: "error",
    name: "EtherTransferNotAllowed",
    inputs: [],
  },
  {
    type: "error",
    name: "ExpectedPause",
    inputs: [],
  },
  {
    type: "error",
    name: "FailedCall",
    inputs: [],
  },
  {
    type: "error",
    name: "FeeAccrualWouldConsumePosition",
    inputs: [
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "positionAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "feeAmount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "GovernanceTimelockAdminRetained",
    inputs: [
      {
        name: "candidate",
        type: "address",
        internalType: "address",
      },
      {
        name: "retainedAdmin",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "GovernanceTimelockDelayTooLong",
    inputs: [
      {
        name: "candidate",
        type: "address",
        internalType: "address",
      },
      {
        name: "delay",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxDelay",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "GovernanceTimelockDelayTooShort",
    inputs: [
      {
        name: "candidate",
        type: "address",
        internalType: "address",
      },
      {
        name: "minDelay",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "GovernanceTimelockHasExtraAdmins",
    inputs: [
      {
        name: "candidate",
        type: "address",
        internalType: "address",
      },
      {
        name: "adminCount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "GovernanceTimelockImplementationMismatch",
    inputs: [
      {
        name: "candidate",
        type: "address",
        internalType: "address",
      },
      {
        name: "expectedCodehash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "actualCodehash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "GovernanceTimelockInvalidRoleMemberCount",
    inputs: [
      {
        name: "candidate",
        type: "address",
        internalType: "address",
      },
      {
        name: "role",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "memberCount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "GovernanceTimelockRoleMemberMismatch",
    inputs: [
      {
        name: "candidate",
        type: "address",
        internalType: "address",
      },
      {
        name: "role",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "expectedMember",
        type: "address",
        internalType: "address",
      },
      {
        name: "actualMember",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "GovernanceZeroAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "IncompatibleShieldedTokenForCrossAssetWithdrawal",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientDepositAmount",
    inputs: [],
  },
  {
    type: "error",
    name: "InsufficientPoolTimeWithDetails",
    inputs: [
      {
        name: "requiredTime",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "elapsedTime",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientProtectorTokenBalance",
    inputs: [],
  },
  {
    type: "error",
    name: "InsufficientTokenBalance",
    inputs: [],
  },
  {
    type: "error",
    name: "InsufficientUnlockedTokens",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidAccessControlAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidAssetAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidCollateralRatio",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidCommissionRate",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidDepositAmountBounds",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidGovernanceTimelock",
    inputs: [
      {
        name: "candidate",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidInitialization",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidMinimumPoolTime",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidOraclePrice",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidPoolCreator",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidPoolFee",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidProtocolFee",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidProtocolFeeRecipient",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidTokenAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidTokenDecimals",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "decimals",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidTokenId",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidUnlockDuration",
    inputs: [],
  },
  {
    type: "error",
    name: "NoPendingGovernance",
    inputs: [],
  },
  {
    type: "error",
    name: "NoTokensToWithdraw",
    inputs: [],
  },
  {
    type: "error",
    name: "NoUnlockToCancel",
    inputs: [],
  },
  {
    type: "error",
    name: "NotInitializing",
    inputs: [],
  },
  {
    type: "error",
    name: "NotOwner",
    inputs: [],
  },
  {
    type: "error",
    name: "OraclePendingChallenge",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "PartialWithdrawalBelowMinimum",
    inputs: [],
  },
  {
    type: "error",
    name: "PoolNotActive",
    inputs: [],
  },
  {
    type: "error",
    name: "PoolNotEmptyForDeactivation",
    inputs: [],
  },
  {
    type: "error",
    name: "ProtectorShareLimitExceeded",
    inputs: [
      {
        name: "shares",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxShares",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ReentrancyGuardReentrantCall",
    inputs: [],
  },
  {
    type: "error",
    name: "RewardAccumulationIncomplete",
    inputs: [
      {
        name: "expected",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "accumulated",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "redirected",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ShieldedFeePriceUnavailable",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "SlippageProtectionFailed",
    inputs: [
      {
        name: "minExpected",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "actualReceived",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "TVLLimitExceeded",
    inputs: [],
  },
  {
    type: "error",
    name: "TransferIntegrityProbeRequired",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "TransferOperationFailed",
    inputs: [],
  },
  {
    type: "error",
    name: "UUPSUnauthorizedCallContext",
    inputs: [],
  },
  {
    type: "error",
    name: "UUPSUnsupportedProxiableUUID",
    inputs: [
      {
        name: "slot",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "UnauthorizedGovernance",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "UnauthorizedPendingGovernance",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "UnexpectedOutboundTransferAmount",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "expectedDebited",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "actualDebited",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "UnlockProcessAlreadyStarted",
    inputs: [],
  },
  {
    type: "error",
    name: "UnsupportedAsset",
    inputs: [],
  },
  {
    type: "error",
    name: "UpgradeDisabled",
    inputs: [],
  },
] as const;
